### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by PowZone** [StanislavPetrovV/DOOM-Level-Viewer#1]
Hello,
I get this error trying to run main.py :

```
pygame 2.4.0 (SDL 2.26.4, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    doom = DoomEngine()
  File "main.py", line 20, in __init__
    self.on_init()
  File "main.py", line 23, in on_init
    self.wad_data = WADData(self, map_name='E1M1')
  File "C:\tmp\DOOM-Level-Viewer-main\wad_data.py", line 61, in __init__
    self.asset_data = AssetData(self)
  File "C:\tmp\DOOM-Level-Viewer-main\asset_data.py", line 141, in __init__
    self.textures |= self.get_flats()
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'
```

p.s.: this project is super cool! I saw the videos on YT

**Comment by Rudicito** [comment]
If you're still alive, it's because `|=` operand for dictionary was introduced in python 3.9, and you're in python 3.8.10. 
https://docs.python.org/3.9/whatsnew/3.9.html#dictionary-merge-update-operators

Just update your python and it should be okay.
